server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/signer?useUnicode=true&characterEncoding=utf8&createDatabaseIfNotExist=true
    username: root
    password: rootpassword

---
spring:
  profiles: dev

logging:
  level:
    org.lunchpicker: debug