server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lunchpicker?useUnicode=true&characterEncoding=utf8&createDatabaseIfNotExist=true
    username: root
    password: rootpassword

lunchpicker:
  user:
    votes: 10

---
spring:
  profiles: dev

logging:
  level:
    org.lunchpicker: debug
